# -*- snakemake -*-

import yaml

samples = [
    'treated1',
    'treated2',
    #'treated3',
    'untreated1',
    'untreated2',
    #'untreated3',
    #'untreated4'
]
HERE = srcdir('')

# relative to the directory of the current snakefile.
WRAPPERS = '../wrappers'


def wrapper_for(tool):
    """
    Returns the wrapper directory for the specified tool
    """
    return os.path.join(HERE, WRAPPERS, tool)

rule all:
    input: expand('pasilla/{sample}/{sample}.fastqc.html', sample=samples)

rule fastqc:
    input: 'pasilla/{sample}/{sample}_R1.fastq.gz'
    output:
        html='pasilla/{sample}/{sample}.fastqc.html',
        zip='pasilla/{sample}/{sample}_fastqc.zip',
    wrapper:
        wrapper_for('fastqc')

# vim: ft=python
