sampletable: pasilla_sampletable.tsv
sample_dir: pasilla
assembly: dm6
data_dir: references

rawLevel: 'pasilla/{sampleID}/{sampleID}_R1'
runLevel: 'pasilla/{sampleID}/{sampleID}_R1'
sampleLevel: 'pasilla/{sampleID}/{sampleID}'
aggLevel: 'pasilla/agg/{treatment}'

shell_prefix: "source lcdb-workflows.bashrc; "
cluster_default:
  args: "--time=04:00:00"

rules:
  kallisto_quant:
    index: 'dm6/kallisto/dm6_r6-11_transcriptome.idx'
    params:
      extra: '--single --fragment-length=200 --sd=20 --bootstrap-samples=100'

  sleuth:
    model: "~treatment"

references:

  -
    assembly: 'dm6'
    type: 'gtf'
    url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/gtf/dmel-all-r6.11.gtf.gz'
    postprocess: "dm6.gtf_postprocess"
    tag: 'r6-11'
    conversions:
      - 'intergenic'
  -
    assembly: 'dm6'
    type: 'fasta'
    tag: 'r6-11_transcriptome'
    url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/fasta/dmel-all-transcript-r6.11.fasta.gz'
    indexes:
      - 'kallisto'
