os:
  - linux

language: c

sudo: required

services:
  - docker

before_install:
  - docker pull continuumio/anaconda

script: docker run -it -v $(pwd):/tmp continuumio/anaconda /bin/bash /tmp/travis-test.sh
