os:
  - linux

language: c

sudo: required

services:
  - docker

before_install:
  - docker pull daler/lcdb-workflows

script: docker run -it -v $(pwd):/opt/lcdb daler/lcdb-workflows /bin/bash travis-test.sh
